### PR TITLE
Reducing the formation time in MS Access

### PR DESCRIPTION
**Pull request by VASilaev**
Reducing the formation time in MS Access

### CODE REVIEW

**Comment by wqweto** [comment]
Which version of MS Access is this fix tested on? I'm interested in the root cause for the performance problems of this particular `CopyMemory` API call.

Also I find it highly unlikely this will speed up VB6 compiled code as each array member access will be bounds check in IDE and probably in compiled binary too.

**Comment by VASilaev** [comment]
Use Access 2016

Test Code:
```vb
Sub TestPerfomance()
  Dim t, qr
  t = Time()
  qr = QRCodegenConvertToData(QRCodegenBarcode(Space(1024), SquareModules:=True), 1000, 1000)
  Debug.Print (Time() - t) * 86400
End Sub
```

Original timing: 112 sec

New timing: 3 sec

**Comment by wqweto** [comment]
> Use Access 2016

Is this x64 or x86 edition?

**Comment by VASilaev** [comment]
For me too.

Tested on MS Access 2010 x32, MS Access 2016 x64, MS Access 2019 x64 - the results are the same everywhere. Performance drops with CopyMemory.

**Comment by VASilaev** [comment]
Maybe it is possible to add conditional compilation for VBA? With different copying methods.

**Comment by wqweto** [comment]
Just tested w/ MS Access 2013 x64

    24.863 -- CopyMemory
    20.945 -- Assignment

It's probably some x64 regression w/ the API call (for a nice 20% speed up).

Wondering where 113 sec vs 3 sec difference in MS Access 2016 comes from.

**Comment by VASilaev** [comment]
I checked it on another computer. Win7 x64 + Office x32 is installed. Both options work equally fast. It's not clear.

Replaced on line 906. Win10 x64 + Office 2019 x64.  Time - 28 ms. it is very good.

**Comment by VASilaev** [comment]
On 906 maybe without copymemory?

```vb
        lDegree = lDegree - 1
        For lJdx = 0 To lDegree
            If lJdx = lDegree Then
               baResult(lJdx) = pvReedSolomonMultiply(baGen(lJdx), bFactor)
            Else
               baResult(lJdx) = baResult(lJdx + 1) Xor pvReedSolomonMultiply(baGen(lJdx), bFactor)
            End If
        Next
```

**Comment by wqweto** [comment]
10x, merged!

**Pull request merged**
